import { StyleSheet, Platform } from 'react-native';

const globalStyles = StyleSheet.create({
    scrollView: {
        flex: 1,
        padding: 15,
        backgroundColor: '#f5f5f5',
    },
    section: {
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 15,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 3,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
        color: '#3498db',
    },
    input: {
        width: '100%',
        height: 50,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 5,
        marginBottom: 20,
        paddingHorizontal: 15,
        backgroundColor: '#fdfdfd',
        fontSize: 16,
    },
    textArea: {
        width: '100%',
        height: 120,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 5,
        marginBottom: 20,
        paddingHorizontal: 15,
        paddingTop: 15,
        backgroundColor: '#fdfdfd',
        textAlignVertical: 'top',
        fontSize: 16,
    },
    label: {
        fontSize: 16,
        marginBottom: 5,
        fontWeight: '500',
        color: '#333',
    },
    formGroup: {
        marginBottom: 15,
    },
    operationTimeGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    timeText: {
        flex: 1,
        padding: 10,
        backgroundColor: '#f0f0f0',
        borderRadius: 5,
        marginRight: 10,
    },
    timeButton: {
        backgroundColor: '#3498db',
        padding: 10,
        borderRadius: 5,
    },
    pickerContainer: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 5,
        marginBottom: 15,
        backgroundColor: '#fdfdfd',
    },
    picker: {
        height: 45,
        width: '100%',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
        flexWrap: 'wrap',
    },
    button: {
        backgroundColor: '#3498db',
        padding: 12,
        borderRadius: 5,
        alignItems: 'center',
        marginVertical: 5,
        flex: 1,
        marginHorizontal: 5,
        minWidth: '45%',
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    disabledButton: {
        backgroundColor: '#bdc3c7',
    },
    dangerButton: {
        backgroundColor: '#e74c3c',
    },
    historyItem: {
        backgroundColor: '#f9f9f9',
        padding: 15,
        borderRadius: 5,
        marginBottom: 10,
        borderLeftWidth: 5,
        borderLeftColor: '#3498db',
    },
    historyTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    emptyHistory: {
        textAlign: 'center',
        padding: 20,
        color: '#7f8c8d',
        fontStyle: 'italic',
    },
    infoCard: {
        backgroundColor: '#e8f4fc',
        padding: 15,
        borderRadius: 5,
        marginVertical: 10,
        borderLeftWidth: 3,
        borderLeftColor: '#3498db',
    },
    infoTitle: {
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 5,
        color: '#2980b9',
    },
    timeItem: {
        marginVertical: 10,
        paddingLeft: 10,
        borderLeftWidth: 2,
        borderLeftColor: '#2980b9',
    },
    totalTime: {
        marginTop: 10,
        fontWeight: 'bold',
        fontSize: 16,
        color: '#2980b9',
    },
});

export default globalStyles;